server:
  port: 9001
eureka:
  instance:
    appname: EUREKA_SERVER
    hostname: euk1.com
  server:
    enable-self-preservation: true
    #my-url: eurekaserver

  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://euk2.com:9002/eureka/

